packages:
  brew:
    - bat
    - fd
    - fzf
    - git-delta
    - gnu-sed
    - gnu-time
    - go
    - gopls
    - jj
    - jq
    - md5sha1sum
    - neovim
    - nmap
    - node
    - pipx
    - python3
    - ripgrep
    - tmux
    - tree
    - wget
  brewCasks:
    - bitwarden
    - rectangle
    - signal
    - wezterm
  go:
    - golang.org/x/tools/gopls
    - github.com/sqls-server/sqls
    - github.com/go-task/task/v3/cmd/task
  npm:
    - '@anthropic-ai/claude-code'
    - bash-language-server
    - typescript-language-server
    - vim-language-server
    - vscode-langservers-extracted
  pipx:
    - httpie
    - install-release
    - powerline-status
  winget:
    - Adobe.Acrobat.Reader.32-bit
    - AutoHotkey.AutoHotkey
    - Bitwarden.Bitwarden
    - CoreyButler.NVMforWindows
    - dandavison.delta
    - Discord.Discord
    - EaseUS.TodoBackup
    - Git.Git
    - Google.Chrome.EXE
    - Google.QuickShare
    - Microsoft.PowerShell
    - Microsoft.PowerToys
    - OpenWhisperSystems.Signal
    - Python.Launcher
    - Spotify.Spotify
    - Tailscale.Tailscale
    - TheDocumentFoundation.LibreOffice
    - Valve.Steam
    - VideoLAN.VLC
    - WinDirStat.WinDirStat
    - dorssel.usbipd-win
    - wez.wezterm
