packages:
  brew:
    - bat
    - fd
    - fzf
    - git-delta
    - gnu-sed
    - gnu-time
    - go
    - gopls
    - jj
    - jq
    - md5sha1sum
    - neovim
    - nmap
    - node
    - pipx
    - python3
    - ripgrep
    - shellcheck
    - tmux
    - tree
    - unzip
    - wget
  brewCasks:
    - bitwarden
    - rectangle
    - signal
    - wezterm
  go:
    - github.com/go-task/task/v3/cmd/task
    - github.com/nao1215/gup
    - github.com/sqls-server/sqls
    - golang.org/x/tools/gopls
    - github.com/idursun/jjui/cmd/jjui
    - mvdan.cc/sh/v3/cmd/shfmt
  npm:
    - bash-language-server
    - "@typescript/native-preview"
    - vim-language-server
    - vscode-langservers-extracted
  pipx:
    - httpie
    - litecli
    - powerline-status
    - pyright
  winget:
    - Adobe.Acrobat.Reader.32-bit
    - AutoHotkey.AutoHotkey
    - Bitwarden.Bitwarden
    - CoreyButler.NVMforWindows
    - dandavison.delta
    - Discord.Discord
    - EaseUS.TodoBackup
    - Git.Git
    - Google.Chrome.EXE
    - Google.QuickShare
    - Microsoft.PowerShell
    - Microsoft.PowerToys
    - Microsoft.VisualStudio.2022.BuildTools
    - OpenWhisperSystems.Signal
    - Python.Launcher
    - rustup
    - Spotify.Spotify
    - Tailscale.Tailscale
    - TheDocumentFoundation.LibreOffice
    - Valve.Steam
    - VideoLAN.VLC
    - WinDirStat.WinDirStat
    - dorssel.usbipd-win
    - wez.wezterm
