packages:
  apt:
    - bat
    - build-essential
    - clang
    - cmake
    - curl
    - direnv
    - fd-find
    - fzf
    - git
    - htop
    - jq
    - neovim
    - pipx
    - python3-dev
    - python3-neovim
    - python3-pip
    - ripgrep
    - tmux
    - tree
  aptDesktop:
    - compizconfig-settings-manager
    - fonts-inconsolata
    - gnome-tweak-tool
  npm:
    - '@anthropic-ai/claude-code'
    - bash-language-server
    - typescript-language-server
    - vim-language-server
    - vscode-langservers-extracted
  pipx:
    - httpie
    - install-release
    - powerline-status
  winget:
    - Adobe.Acrobat.Reader.32-bit
    - AutoHotkey.AutoHotkey
    - Bitwarden.Bitwarden
    - CoreyButler.NVMforWindows
    - dandavison.delta
    - Discord.Discord
    - EaseUS.TodoBackup
    - Git.Git
    - Google.Chrome.EXE
    - Google.QuickShare
    - Microsoft.PowerShell
    - Microsoft.PowerToys
    - OpenWhisperSystems.Signal
    - Python.Launcher
    - Spotify.Spotify
    - Tailscale.Tailscale
    - TheDocumentFoundation.LibreOffice
    - Valve.Steam
    - VideoLAN.VLC
    - WinDirStat.WinDirStat
    - dorssel.usbipd-win
    - wez.wezterm
