packages:
  apt:
    - bat
    - build-essential
    - clang
    - cmake
    - curl
    - direnv
    - fd-find
    - fzf
    - git
    - htop
    - jq
    - neovim
    - pipx
    - python3-dev
    - python3-neovim
    - python3-pip
    - ripgrep
    - tmux
    - tree
  aptDesktop:
    - compizconfig-settings-manager
    - fonts-inconsolata
    - gnome-tweak-tool
  npm:
    - '@anthropic-ai/claude-code'
    - bash-language-server
    - typescript-language-server
    - vim-language-server
    - vscode-langservers-extracted
  pipx:
    - httpie
    - install-release
    - powerline-status
