[user]
name = "Nik Klassen"
email = "nikklassen@users.noreply.github.com"

[ui]

merge-editor = "nvimdiff"
# diff.format = "git"
diff-formatter = "delta"

# diff-editor = "diffedit3"
# diff-editor = ":builtin"
diff-editor = "hunk"

# diff.format = "git"
pager = ["less", "-FRX", "--quit-if-one-screen"]

[merge-tools.delta]
diff-expected-exit-codes = [0, 1]

[merge-tools.diffedit3]

merge-args = ["-N", "-p", "17376-17380", "$left", "$right", "$output"]
edit-args = ["-N", "-p", "17376-17380", "$left", "$right", "$output"]

[merge-tools.hunk]

program = "nvim"
edit-args = ["-c", "DiffEditor $left $right $output"]

[merge-tools.nvimdiff]

# merge-args = [ "-c", "DiffConflicts", "$output", "$base", "$left", "$right" ]
merge-args = ["-u", "NONE", "-f", "-d", "$output", "-M",
    "$left", "$base", "$right",
    "-c", "wincmd J", "-c", "set modifiable",
    "-c", "set write"]
program = "nvim"
merge-tool-edits-conflict-markers = true

# [merge-tools.delta]
#
# merge-args = ["$left", "$right", "--paging", "always"]

[template-aliases]

'format_timestamp(timestamp)' = 'timestamp.ago()'
'format_short_signature(signature)' = 'signature.email().local()'

[snapshot]

auto-update-stale = true

[git]

auto-local-bookmark = true
