# Setting PATH for Python 2.7
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

# MacPorts Installer addition on 2012-11-19_at_19:38:15: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH

# Setup rbenv
export PATH="$HOME/.rbenv/bin:$PATH"

eval "$(rbenv init -)"
rbenv local 2.0.0-p195

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
