alias ls="ls -FG"
alias grep="egrep --color"
alias cdt="cd ~/Movies/TV\ Shows"
alias cdp='cd ~/Programming'
alias mount='hdiutil mount'
alias eject='hdiutil eject'

alias parent='source parent'

alias gst='git status'

alias irb='irb --simple-prompt'
alias cowsay='cowsay -f vader-koala'

export EDITOR=vim
